# Generated by Django 2.1.7 on 2019-04-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penpal_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proficiency',
            name='level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)]),
        ),
    ]
