# Generated by Django 2.1.7 on 2019-03-31 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('penpal_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('averageProficiency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('fromUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagesSent', to='penpal_app.User')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagesLanguage', to='penpal_app.Language')),
                ('toUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messagesRecieved', to='penpal_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Proficiencie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], unique=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='penpal_app.Language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='penpal_app.User')),
            ],
        ),
    ]
