# Generated by Django 2.1.7 on 2019-03-31 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('penpal_app', '0002_language_message_proficiencie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proficiencie',
            new_name='Proficiency',
        ),
    ]
